version: '3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=achatdb
      - MYSQL_ROOT_PASSWORD=
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  achat-backend-app:
    container_name: achat-backend-app
    depends_on:
      - mysqldb
    image: siwara/timesheet-devops:1.0.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=

    
volumes:
  db: