version: '3.8'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=achatdb
      - MYSQL_HOST=mysqldb
    networks:
      - net-mysql
    volumes:
      - mysql_data:/var/lib/mysql

  achat-backend-app:
    container_name: achat-backend-app
    depends_on:
      - mysqldb
    image: imenchanoufi/achatback:v1.1
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpass
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5Dialect
      - SERVER_SERVLET_CONTEXT_PATH=/SpringMVC
    stdin_open: true
    tty: true
    networks:
      - net-mysql

  achat-frontend-app:
    container_name: achat-frontend-app
    image: imenchanoufi/achatfront:v2.2
    restart: on-failure
    ports:
      - "4300:80"
    networks:
      - net-mysql
volumes:
  mysql_data:
networks:
  net-mysql:
    driver: bridge
    attachable: true
